name: Build Docker image for demo app

on: [workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_NAMESPACE: jcdb
  DOCKERHUB_IMAGE_NAME: jcdb-demo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'liberica'
          java-package: jdk+fx

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.8

      - name: Build with Gradle
        run: gradle clean bootJar

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PUBLISH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        if: ${{ github.event_name != 'pull_request' }}
        with:
          push: true
          # read more about contexts at:
          #   https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          tags: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.DOCKERHUB_IMAGE_NAME }}:${{ github.sha }}
          context: .
          file: jcdb-http/Dockerfile
